### ISSUE TITLE
wrong file loading

### ISSUE THREAD

**Issue by nitosiak** [efekos/minecraft-project-manager#1]
**Describe the bug**
your extension tries to load the wrong file its inside the saves folder and it dosent exist and i dind even open it in VScode

**To Reproduce**
idk

**Expected behavior**
an error to apear 
EONET: no such file or directory scandir
'C:\Users<username>\AppdData\Roaming\.minecraft\saves/<the non existing file that is trying to load>

**Screenshots**

![error](https://github.com/efekos/minecraft-project-manager/assets/105192288/bad99438-e778-40f5-9f49-334abb3af1aa)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [microsoft edge]
 - Version [1.0.0,1.0.1]

**Smartphone (please complete the following information):**
no

**Additional context**

**Comment by efekos** [comment]
It should be fixed in 1.0.2. If you still encounter same or similiar issues, open a new issue with more details.
